In [1]:
import pandas as pd

In [2]:
npr=pd.read_csv('train.csv')

In [3]:
npr.head()

posting_id                                 image       image_phash  \
0   train_129225211  0000a68812bc7e98c42888dfb1c07da0.jpg  94974f937d4c2433   
1  train_3386243561  00039780dfc94d01db8676fe789ecd05.jpg  af3f9460c2838f0f   
2  train_2288590299  000a190fdd715a2a36faed16e2c65df7.jpg  b94cb00ed3e50f78   
3  train_2406599165  00117e4fc239b1b641ff08340b429633.jpg  8514fc58eafea283   
4  train_3369186413  00136d1cf4edede0203f32f05f660588.jpg  a6f319f924ad708c   

                                               title  label_group  
0                          Paper Bag Victoria Secret    249114794  
1  Double Tape 3M VHB 12 mm x 4,5 m ORIGINAL / DO...   2937985045  
2        Maling TTS Canned Pork Luncheon Meat 397 gr   2395904891  
3  Daster Batik Lengan pendek - Motif Acak / Camp...   4093212188  
4                  Nescafe \xc3\x89clair Latte 220ml   3648931069

In [4]:
npr['title'][0]

'Paper Bag Victoria Secret'

In [5]:
len(npr)

34250

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
cv=CountVectorizer(max_df=0.9, min_df=2, stop_words='english')

In [8]:
dtm=cv.fit_transform(npr['title'])

In [9]:
dtm

<34250x15172 sparse matrix of type '<class 'numpy.int64'>'
	with 266990 stored elements in Compressed Sparse Row format>

In [10]:
from sklearn.decomposition import LatentDirichletAllocation

In [11]:
LDA = LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                                evaluate_every=-1, learning_decay=0.7, 
                                learning_method='batch', learning_offset=10.0, 
                                max_doc_update_iter=100, max_iter=10, mean_change_tol=0.001,
                                n_components=10, n_jobs=None, perp_tol=0.1,
                                random_state=42, topic_word_prior=None, total_samples=1000000.0,
                               verbose=0)

In [12]:
LDA.fit(dtm)

LatentDirichletAllocation(random_state=42)

In [13]:
#Grab the vocabulary of words, topics, and highest probability words per topic

In [14]:
#Grab the vocabulary of words

In [15]:
len(cv.get_feature_names_out())

15172

In [16]:
type(cv.get_feature_names_out())

numpy.ndarray

In [17]:
cv.get_feature_names()[3927]

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


'coda'

In [18]:
import random

random_word = random.randint(0,15172)

cv.get_feature_names()[random_word]

'reverse'

In [19]:
#Grab topics

In [20]:
len(LDA.components_)

10

In [21]:
type(LDA.components_)

numpy.ndarray

In [22]:
LDA.components_.shape

(10, 15172)

In [23]:
LDA.components_

array([[ 0.10000749,  0.10000722,  0.10001121, ...,  0.1       ,
         0.1       ,  0.1       ],
       [ 0.10000075,  0.1       ,  0.1       , ...,  0.10001006,
         0.10000138,  0.1       ],
       [ 0.10000119,  0.10003308,  0.10001721, ...,  2.09998124,
         0.10000185,  0.1       ],
       ...,
       [ 0.10000594, 28.29076726,  1.099965  , ...,  0.1       ,
         0.100001  ,  6.09987587],
       [ 0.23715281,  0.49433573,  0.1       , ...,  0.1       ,
        15.62637828,  0.10002061],
       [ 0.1       ,  0.10001211,  0.1       , ...,  0.10000628,
        16.57359728,  0.10010351]])

In [24]:
single_topic=LDA.components_[0]

In [25]:
single_topic.argsort()
#argsort sort index position from the least to the greatest value

array([  908,  1642,  1650, ...,  5676, 12295,  8638], dtype=int64)

In [26]:
single_topic.argsort()[-10:] 
#grab top 10, last 10 values of argsort

array([10331,  1873,  9252,  1986,  9162,  6494,  4731,  5676, 12295,
        8638], dtype=int64)

In [27]:
top_ten=single_topic.argsort()[-10:] 

In [28]:
for index in top_ten:
    print(cv.get_feature_names()[index])

pcs
alat
mobil
anak
mini
holder
dress
gamis
set
mainan


In [29]:
#Grab highest probability words per topic

In [30]:
for i,topic in enumerate(LDA.components_):
    print(f"THE TOP 10 WORDS FOR TOPIC #{i}")
    print([cv.get_feature_names()[index] for index in topic.argsort()[-10:]])
    print('\n')
    print('\n')

THE TOP 10 WORDS FOR TOPIC #0
['pcs', 'alat', 'mobil', 'anak', 'mini', 'holder', 'dress', 'gamis', 'set', 'mainan']




THE TOP 10 WORDS FOR TOPIC #1
['oppo', 'cover', 'samsung', '11', 'plus', 'iphone', 'anti', 'pro', 'rak', 'case']




THE TOP 10 WORDS FOR TOPIC #2
['resmi', 'speaker', 'earphone', 'garansi', 'charger', 'headset', 'kabel', 'bluetooth', 'original', 'usb']




THE TOP 10 WORDS FOR TOPIC #3
['kain', 'x80', 'cod', 'bag', 'fashion', 'import', 'masker', 'xe2', 'wanita', 'tas']




THE TOP 10 WORDS FOR TOPIC #4
['pisau', 'ml', 'gel', 'rambut', 'gigi', 'alat', 'softlens', 'botol', 'joyko', 'hand']




THE TOP 10 WORDS FOR TOPIC #5
['dan', 'premium', 'motif', 'isi', 'bayi', 'glow', 'original', 'spray', 'buku', 'baby']




THE TOP 10 WORDS FOR TOPIC #6
['topi', 'motif', 'wanita', 'polos', 'rambut', 'untuk', 'kaki', 'kaos', 'bayi', 'anak']




THE TOP 10 WORDS FOR TOPIC #7
['murah', 'sepatu', 'sandal', 'celana', 'sarung', 'wanita', 'baju', 'jam', 'pria', 'tangan']




THE TOP 10 

In [31]:
dtm

<34250x15172 sparse matrix of type '<class 'numpy.int64'>'
	with 266990 stored elements in Compressed Sparse Row format>

In [32]:
topic_results=LDA.transform(dtm)

In [33]:
topic_results.shape

(34250, 10)

In [34]:
topic_results[0].round(2)

array([0.29, 0.02, 0.02, 0.22, 0.02, 0.02, 0.02, 0.02, 0.35, 0.02])

In [35]:
topic_results[0].argmax()

8

In [36]:
npr['Topic']=topic_results.argmax(axis=1)

In [37]:
npr

posting_id                                 image  \
0       train_129225211  0000a68812bc7e98c42888dfb1c07da0.jpg   
1      train_3386243561  00039780dfc94d01db8676fe789ecd05.jpg   
2      train_2288590299  000a190fdd715a2a36faed16e2c65df7.jpg   
3      train_2406599165  00117e4fc239b1b641ff08340b429633.jpg   
4      train_3369186413  00136d1cf4edede0203f32f05f660588.jpg   
...                 ...                                   ...   
34245  train_4028265689  fff1c07ceefc2c970a7964cfb81981c5.jpg   
34246   train_769054909  fff401691371bdcb382a0d9075dfea6a.jpg   
34247   train_614977732  fff421b78fa7284284724baf249f522e.jpg   
34248  train_3630949769  fff51b87916dbfb6d0f8faa01bee67b8.jpg   
34249  train_1792180725  ffffa0ab2ae542357671e96254fa7167.jpg   

            image_phash                                              title  \
0      94974f937d4c2433                          Paper Bag Victoria Secret   
1      af3f9460c2838f0f  Double Tape 3M VHB 12 mm x 4,5 m ORIGINAL / DO...   
2      b94cb00ed3e50f78        Maling TTS Canned Pork Luncheon Meat 397 gr   
3      8514fc58eafea283  Daster Batik Lengan pendek - Motif Acak / Camp...   
4      a6f319f924ad708c                  Nescafe \xc3\x89clair Latte 220ml   
...                 ...                                                ...   
34245  e3cd72389f248f21  Masker Bahan Kain Spunbond Non Woven 75 gsm 3 ...   
34246  be86851f72e2853c    MamyPoko Pants Royal Soft - S 70 - Popok Celana   
34247  ad27f0d08c0fcbf0  KHANZAACC Robot RE101S 1.2mm Subwoofer Bass Me...   
34248  e3b13bd1d896c05c  Kaldu NON MSG HALAL Mama Kamu Ayam Kampung , S...   
34249  af8bc4b2d2cf9083  FLEX TAPE PELAPIS BOCOR / ISOLASI AJAIB / ANTI...   

       label_group  Topic  
0        249114794      8  
1       2937985045      4  
2       2395904891      2  
3       4093212188      3  
4       3648931069      0  
...            ...    ...  
34245   3776555725      3  
34246   2736479533      5  
34247   4101248785      2  
34248   1663538013      5  
34249    459464107      0  

[34250 rows x 6 columns]